{% set name = "redpil" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9ed3318eaed00e3565c8e38e74aec770a45f2e2de500c4800584bc8a8c5d523c

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools
  run:
    - python >=3.10
    - numpy

test:
  imports:
    - redpil
    - redpil.bmp

about:
  home: https://github.com/hmaarrfk/redpil
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Join the wonderland of python, and decode all your images in a numpy compatible way'

extra:
  recipe-maintainers:
    - hmaarrfk
