travis:
  secure:
    BINSTAR_TOKEN: f7vjQlFbu4BDP28NRrK0/naZO388LXRdypqeBSLO6WeFrOMT83S6uqQAy2GXjfvhH5z1s96avs0zqyAsSAb+22XdX2gjUf/yJP9DT3cdhyzWzrCykWVj81OkyxI5PR2IbfIIGLvltmUv2DYLDk48PCW0ivQrVxkAEaZw/ya9PAcWJ29B/o4C5e41nKhN0xHoAVRi6ODfZQAUmheOLF9p4MbGBq0645vZ/lfatipz1TFqs0+6JS3mLJK0VxfVG+vo1rnDn6TuZ3P7x8/Oc/AGsNAwUpUFoTupovlZGCM/e1C5SoVUlijK046RLfabrUf0ORiwPQuWzZQCtEc3UOYWBU9HmoSsrJsL1l20seuBxqdVVsNE6oadwSkGi+L9IJN29zrcKtZUUCMboj4kmkSEzuj/3DJV3JnDfqYMlZysJ7tVWE3bFQCaPo8ZQMKBLpEnqe7D+hFllHU6Wu5r2xhTxwoU8rx4q+2ZtnnXB7WTgCSszx6Lm1SrRUzPSRem+x7DHFd1l/oQjxL7RQYTg99WcAd4eW5fEd/TJtbkEaMh8ZJcdtelOzxQWKHEhVM/iNgP/iD2X1tjA9qgc204TadnvqV8hZGw7UJ4TM0cmk5VJhbkRlWd/MgVewIq1KsuyqmUmOE+dwqZPQPWig2SO50SFS0SoSUTWH6yeHBtgFnm4AE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
